1. The problem is the following error: ```smart_contracts/counter/contract.py:20:9 error: Unresolvable attribute 'count' of smart_contracts.counter.contract.Counter                                                        self.count[Txn.sender] += 1                                                        ^~~~~~~~~~~~~~~~~~~~~~ smart_contracts/counter/contract.py:12:9 error: Unresolvable attribute 'count' of smart_contracts.counter.contract.Counter                                                        self.count[Txn.sender] = UInt64(0)                                                        ^~~~~~~~~~~~~~~~~~~~~~ ``` suggesting the attribute of count has not been properly initiated.
2. In the ```smart_contracts/counter/contract.py``` the class Counter() is missing the initiation function like in the example https://algorandfoundation.github.io/puya/lg-structure.html where you can declare a value.  I fixed it by adding the ```def __init__(self) -> None:
    self.counters = GlobalState(UInt64(0))
    self.count = LocalState(UInt64)
    ```